//user action
export const LOGINED = "LOGINED";
export const LOGINED_SUCCESS = "LOGINED_SUCCESS";
export const LOGINED_ERROR = "LOGINED_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_CLEAR = "SIGNUP_CLEAR";
//관리자 체크
export const ADMIN_CHECK = "ADMIN_CHECK";
export const ADMIN_CHECK_SUCCESS = "ADMIN_CHECK_SCUEESSS";
export const ADMIN_CHECK_ERROR = "ADMIN_CHECK_ERROR";
export const ADMIN_CHECK_CLEAR = "ADMIN_CHECK_CLEAR";
//product action
//제품전체
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
//제품1개조회
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
//상품 등록
export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";
export const POST_PRODUCT_CLEAR = "POST_PRODUCT_CLEAR";
//상품 수정
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
//상품 필터
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const FILTER_PRODUCT_SUCCESS = "FILTER_PRODUCT_SUCCESS";
export const FILTER_PRODUCT_ERROR = "FILTER_PRODUCT_ERROR";
//카트
export const UPDATECART = "UPDATECART";
export const DELETECART = "DELETECART";
export const CHANGE_COUNT_CART = "CHANGE_COUNT_CART";
//admin 상품 정렬
export const ORDER_PRODUCT = "ORDER_PRODUCT";
//admin Search
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_ERROR = "SEARCH_PRODUCT_ERROR";

//배너 전체 조회
export const GET_BANNERS = "GET_BANNERS";
export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS";
export const GET_BANNERS_ERROR = "GET_BANNERS_ERROR";
//배너 1개 조회
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_ERROR = "GET_BANNER_ERROR";
//배너 등록
export const POST_BANNER = "POST_BANNER";
export const POST_BANNER_SUCCESS = "POST_BANNER_SUCCESS";
export const POST_BANNER_ERROR = "POST_BANNER_ERROR";
export const POST_BANNER_CLEAR = "POST_BANNER_CLEAR";
//배너 정렬
export const SORT_BANNER = "SORT_BANNER";
export const SORT_BANNER_SUCCESS = "SORT_BANNER_SUCCESS";
export const SORT_BANNER_ERROR = "SORT_BANNER_ERROR";
//배너 검색
export const SEARCH_BANNER = "SEARCH_BANNER";
export const SEARCH_BANNER_SUCCESS = "SEARCH_BANNER_SUCCESS";
export const SEARCH_BANNER_ERROR = "SEARCH_BANNER_ERROR";
//배너 수정
export const UPDATE_BANNER = "UPDATE_BANNER";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_ERROR = "UPDATE_BANNER_ERROR";

export const DETAIL_BANNER_CLEAR = "DETAIL_BANNER_CLEAR";
