export const CategoryMappingById = {
  1: "유산소-러닝머신",
  2: "유산소-사이클",
  3: "웨이트-바벨",
  4: "웨이트-덤벨",
  5: "웨이트-원판",
  6: "웨이트-머신",
  7: "운동보조기구-밴드",
  8: "운동보조기구-스트랩",
  9: "운동보조기구-벨트",
  10: "마사지기구-폼롤러",
  11: "마사지기구-요가매트",
};
export const CategoryList = [
  "런닝머신",
  "사이클",
  "바벨",
  "덤벨",
  "원판",
  "기구",
  "밴드",
  "스트랩",
  "벨트",
  "폼롤러",
  "요가매트",
];
export const CategoryMapping = {
  런닝머신: "running",
  사이클: "cycle",
  바벨: "babel",
  덤벨: "dumbbell",
  원판: "plate",
  기구: "machine",
  밴드: "band",
  스트랩: "strap",
  벨트: "belt",
  폼롤러: "roller",
  요가매트: "mat",
};
export const CategoryMappingReverse = {
  running: "러닝머신",
  cycle: "사이클",
  babel: "바벨",
  dumbbell: "덤벨",
  plate: "원판",
  machine: "기구",
  band: "밴드",
  strap: "스트랩",
  belt: "밸트",
  roller: "폼롤러",
  mat: " 요가매트",
};
export const CategoryMappingByIdPosted = {
  1: "러닝머신",
  2: "사이클",
  3: "바벨",
  4: "덤벨",
  5: "원판",
  6: "머신",
  7: "밴드",
  8: "스트랩",
  9: "벨트",
  10: "폼롤러",
  11: "요가매트",
};
